version: '3.1'
services:
  app:
    networks:
      - code-former-ui
    image: 'code-former-ui'
    build: .
    restart: unless-stopped
    ports:
      - 9118:5000
    environment:
      PORT: 5000

      CODE_FORMER_PATH: $CODE_FORMER_PATH
      TEMP_DIR: /home/code-former-ui/dump

    volumes:
      - ./codeformer:/home/code-former-ui/dump
      - ./logs:/home/code-former-ui/logs

networks:
  code-former-ui: